import { Inter } from "next/font/google";
import "./globals.css";
import {NextIntlClientProvider, useMessages} from "next-intl";
import Header from "@/components/layout/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: {locale} }) {

    const messages = useMessages();

  return (
    <html lang={locale}>
      <body className={inter.className}>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <main className={`min-h-screen space-y-5 flex flex-col`}>
            <Header/>
            <section className={`flex flex-1`}>
                {children}
            </section>
        </main>
      </NextIntlClientProvider>
      </body>
    </html>
  );
}
